### ISSUE TITLE
[PE-D][Tester D] Remark without any prefix clears remark however this behaviour is not been documented

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-W09-4/tp#116]
Maybe the behaviour of `remark INDEX` without any prefix (optional) can be specified in the user guide?

I understand that I can empty out a remark by inputting an empty string however there was no mention of leaving out the prefix completely (which clears the remark command in this case too).

**Steps to reproduce**:
1) Run `remark 1 r/Great attitude, hardworking`
2) Run `remark 1`

![image.png](https://raw.githubusercontent.com/mfjkri/ped/main/files/ccafdd65-fc04-42dc-8097-020142890730.png)

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: mfjkri/ped#1

**Comment by sk2001git** [comment]
This is actually a very good error spotted, will update this in the UG. Not intended
