### ISSUE TITLE
[PE-D][Tester D] Missing closing parenthesis at end of error message for edit

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-W09-4/tp#122]
I think there should be a closing parenthesis at the end of the error message for edit.

**Steps to reproduce**: 
1) Run `edit 1 sc/123 3`

**Result**:

![image.png](https://raw.githubusercontent.com/mfjkri/ped/main/files/0e56f279-053a-4597-ba65-85e334a21ee6.png)

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: mfjkri/ped#4

**Comment by sk2001git** [comment]
Missing ) for feedback, change in code

**Comment by sk2001git** [comment]
Unable to change in feature freeze, this will be omitted
