### ISSUE TITLE
[PE-D][Tester B] filter percentile calculation

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-W09-4/tp#127]
Having 2 people with the same score of a tag, they are both treated as 0th percentile, and would only show up when i filter by percentile and value being 0. If this is part of the feature, pls do include it in the user guide as currently it states that ` 100.0 would represent the best performing candidate for that tag and percentile 0.0 would represent the worst performing candidate for that tag` so I was expecting both to show up when i filter by percentile with value 100

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: derekjxtan/ped#3

**Comment by sk2001git** [comment]
I will likely correct the UG for this. But again, when you have 2 percentile, it is vacuously true, that they are both the worst and best performing candidate at the same time

**Comment by sk2001git** [comment]
Triaged in UG
