### ISSUE TITLE
[PE-D][Tester B] edit/filter tag bug

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-W09-4/tp#136]
Filter does not do anything and does not show error message, but not sure what it is caused by.

To recreate the bug:
1. add a assessment type tag to a person with a score
2. add the same assessment type tag to another person with a score
3. remove the tag from 1 of the people
4. add the same assessment type tag to the person without a score.

Filter stops working at this point.

![image.png](https://raw.githubusercontent.com/derekjxtan/ped/main/files/cfa58f65-cd86-40f1-be4f-18dd2e6ac7ac.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: derekjxtan/ped#6

**Comment by sk2001git** [comment]
This was a valid error, got target invocation error, so this was a major feature bug.  This was because of how we are trying to access a  tag in a score list when it does not exist, but it is tagged to a person
