### ISSUE TITLE
[PE-D][Tester B] validation checks for add command

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-W09-4/tp#143]
`Add` command doesnt seem to fully validate inputs. For example, I can add 2 people with the same phone number, email and address as long as I change the name. This should be checked and prevented, or at least inform the user that such things have occurred, as this indicates a data issue. This is marked as high severity as data integrity issues are problematic once added to a system.

-------------
Labels: `type.FeatureFlaw` `severity.High`
original: derekjxtan/ped#8

**Comment by sk2001git** [comment]
I think validation is not a problem here. This depends on how u wish to constraint uniqueness. In a sense, name is our unique primary key. This is a design choice where we only ensure exact duplicates do not exist. However, the amount of flexibility we wish to give to hiring manager would make these design choice justifiable.
